version: '3.0'
services:
  rasa_english:
    container_name: "rasa_server_english"
    build:
      context: ./bot-english
    volumes:
      - "./bot-english:/app/bot-english"
    ports:
      - "5005:5005"
  # depends_on:
  #   - action_server
  #   - duckling_server
  rasa_german:
    container_name: "rasa_server_german"
    build:
      context: ./bot-german
    volumes:
      - "./bot-german:/app/bot-german"
    ports:
      - "5006:5006"
  # depends_on:
  #   - rasa_english
  rasa_greek:
    container_name: "rasa_server_greek"
    build:
      context: ./bot-greek
    volumes:
      - "./bot-greek:/app/bot-greek"
    ports:
      - "5007:5007"
    # depends_on:
    #   - rasa_english
  rasa_spanish:
    container_name: "rasa_server_spanish"
    build:
      context: ./bot-spanish
    volumes:
      - "./bot-spanish:/app/bot-spanish"
    ports:
      - "5008:5008"
    # depends_on:
    #   - rasa_english
  action_server:
    container_name: "action_server"
    build:
      context: actions
    volumes:
      - ./actions:/app/actions
      - ./data:/app/data
    ports:
      - "5055:5055"
  duckling_server:
    container_name: "duckling_server"
    image: rasa/duckling:latest
    ports:
      - "8000:8000"
  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./conf.d:/etc/nginx/conf.d
  #   depends_on:
  #     - action_server
  #   ports:
  #     - "5055:5055"
